steps:
  # Docker image'ı build et
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/edevlet-belge-dogrulama-api:$COMMIT_SHA',
        '.',
      ]

  # Docker image'ı push et
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/edevlet-belge-dogrulama-api:$COMMIT_SHA']

  # Cloud Run'a deploy et
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'edevlet-belge-dogrulama-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/edevlet-belge-dogrulama-api:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '10'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'

images:
  - 'gcr.io/$PROJECT_ID/edevlet-belge-dogrulama-api:$COMMIT_SHA'
